### ISSUE TITLE
Перенести дані про документи з documents.csv до мета-файлів

### ISSUE THREAD

**Issue by grsmv** [open-budget/api#30]
Створити та читати файли з наступною структурою:

```yaml

name:        "Видатки обласного бюджету на 2014 рік за тимчасовою (...)"
description: "Додаток 2 до рішення 21 сесії обласної Ради 6 скликання від (...)"
source:      "Рішення про обласний бюджет на 2014 рік"
link:        "http://www.oda.ck.ua/docs/budget/bud2014.pdf"
```

Зберігати подібні мета-файли в тій саме директорії, що і таблиці видатків
